### ISSUE TITLE
Kanbanboard

### ISSUE THREAD

**Issue by shahira-sadat** [shahira-sadat/Recipe-app#8]
[Recipe Project](https://github.com/shahira-sadat/Recipe-app)
[Kanban Board](https://github.com/users/shahira-sadat/projects/5)
We are two people in this project:
@shahira-sadat 
@aizjicod

**Comment by brytebee** [comment]
Hi, Team👋,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

# Status: Invalid Code Review Request

![](https://media.giphy.com/media/OQeKGexhYKVjLaSzPd/giphy.gif)

You have submitted a project, whose link does not point to the kanban board but to the readme. The repo doesn't contain an open project. Kindly check if the repo/kanban is private and ensure it is public.
![image](https://user-images.githubusercontent.com/27709832/200342183-ea224c06-fada-4f62-b5fa-43fe185889ce.png)


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by brytebee** [comment]
Hi Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

Good job so far coming so far with the progress you've made! 💪💪
 
However, there are some issues that you still need to work on to go to the next project but you are almost there!

![](https://media.giphy.com/media/VL48WGMDjD64umCEkv/giphy.gif)

# Required Changes ♻️
- You have missed the card to handle N+1 problems [in the project requirement](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements). Kindly add this card.

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Please, remember to tag me in your question so I can receive the notification.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_


**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by brytebee** [comment]
Hi, Team👋,

##

### Highlights💡
- A link to the Kanban board is specified.✔️ 
- The team member size is stated.✔️
- All required columns are present.✔️
- Cards are distributed fairly.✔️

##

# STATUS: APPROVED 🕺🥳 

Congratulations🍾🥳!! Your project is ready for presentation!  There is nothing else to say other than... it's time to merge it :shipit: 

![](https://media.giphy.com/media/vmtxnxveVUodG/giphy.gif)

##

###  **Optional Suggestions:**
- N/A

##

Good luck! 🎉 

------

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @brytebee in your question so I can receive the notification.
### _**Use @brytebee on slack for faster responses.**_

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
